export const staticItems = [
  {
    id: '1',
    title: 'Wireless Noise-Cancelling Headphones',
    shortDescription: 'Premium sound with 30hr battery life and adaptive noise cancellation.',
    fullDescription: 'Experience audio like never before with these flagship wireless headphones. Featuring industry-leading noise cancellation technology, a 30-hour battery, and plush ear cushions for all-day comfort. Connects via Bluetooth 5.2 with multipoint pairing for up to 3 devices simultaneously.',
    price: 299,
    category: 'Electronics',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop',
    specs: { Brand: 'SoundMax', Connectivity: 'Bluetooth 5.2', Battery: '30 hours', Weight: '250g' },
  },
  {
    id: '2',
    title: 'Mechanical Keyboard RGB',
    shortDescription: 'Tactile switches with full RGB backlighting and USB-C connectivity.',
    fullDescription: 'A premium 75% mechanical keyboard built for coders and gamers. Uses Cherry MX Red switches for smooth, fast actuation. The per-key RGB lighting is fully customizable via companion software. Durable aluminum frame, detachable USB-C cable.',
    price: 149,
    category: 'Electronics',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=400&h=300&fit=crop',
    specs: { Switch: 'Cherry MX Red', Layout: '75%', Backlight: 'RGB', Connection: 'USB-C' },
  },
  {
    id: '3',
    title: 'Minimalist Leather Wallet',
    shortDescription: 'Slim 6-card wallet crafted from full-grain leather. RFID protected.',
    fullDescription: 'Handcrafted from full-grain Italian leather, this slim wallet holds up to 6 cards plus a cash sleeve. RFID blocking technology protects your cards from unauthorized scanning. Gets better with age as the leather develops a natural patina.',
    price: 59,
    category: 'Accessories',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&h=300&fit=crop',
    specs: { Material: 'Full-grain leather', Capacity: '6 cards + cash', RFID: 'Yes', Colors: 'Brown, Black, Tan' },
  },
  {
    id: '4',
    title: 'Stainless Steel Water Bottle',
    shortDescription: 'Triple-insulated 32oz bottle keeps drinks cold 24h, hot 12h.',
    fullDescription: 'This 32oz stainless steel bottle uses triple-wall vacuum insulation to keep your drinks at the perfect temperature all day. The wide mouth accepts ice cubes, and the leak-proof lid features a carrying handle. BPA-free and dishwasher safe.',
    price: 39,
    category: 'Lifestyle',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=300&fit=crop',
    specs: { Capacity: '32oz / 946ml', Insulation: 'Triple-wall', Material: 'Stainless steel', BPA: 'Free' },
  },
  {
    id: '5',
    title: 'Portable Laptop Stand',
    shortDescription: 'Adjustable aluminum stand compatible with 10–17" laptops.',
    fullDescription: 'Elevate your workspace with this ultra-portable aluminum laptop stand. Six height settings let you dial in the perfect ergonomic angle. Folds flat to fit in any bag. The non-slip silicone pads protect your desk and laptop surface.',
    price: 49,
    category: 'Accessories',
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=300&fit=crop',
    specs: { Material: 'Aluminum', Compatibility: '10–17" laptops', Settings: '6 height levels', Weight: '350g' },
  },
  {
    id: '6',
    title: 'Scented Soy Candle Set',
    shortDescription: 'Set of 3 hand-poured soy candles. 40h burn time each. Gift-ready.',
    fullDescription: 'This curated set of 3 soy wax candles features calming scents: Cedarwood & Vanilla, Ocean Breeze, and Lavender Fields. Each candle provides up to 40 hours of clean burn time. Hand-poured in small batches, lead-free cotton wicks, and packaged in a beautiful gift box.',
    price: 45,
    category: 'Lifestyle',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1603905460081-fd98afde4b49?w=400&h=300&fit=crop',
    specs: { Count: '3 candles', Wax: '100% soy', Burn: '40h each', Wicks: 'Lead-free cotton' },
  },
  {
    id: '7',
    title: 'Smart LED Desk Lamp',
    shortDescription: 'Touch-controlled lamp with 5 color temps, USB charging port, and timer.',
    fullDescription: 'Illuminate your workspace intelligently with this smart LED desk lamp. Choose from 5 color temperatures (2700K–6500K) and 10 brightness levels via touch control. The built-in USB-A port charges your devices. Auto-timer shuts off the lamp after 1 hour.',
    price: 69,
    category: 'Electronics',
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=300&fit=crop',
    specs: { 'Color Temps': '5 modes', Brightness: '10 levels', 'USB Port': 'USB-A', Timer: '1 hour auto-off' },
  },
  {
    id: '8',
    title: 'Yoga Mat Premium',
    shortDescription: 'Non-slip 6mm thick mat with alignment lines. Eco-friendly materials.',
    fullDescription: 'Crafted from eco-friendly natural rubber and microfiber, this mat provides excellent grip even during sweaty sessions. The 6mm thickness cushions joints without sacrificing stability. Alignment lines help perfect your form. Comes with a carrying strap.',
    price: 85,
    category: 'Lifestyle',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=300&fit=crop',
    specs: { Material: 'Natural rubber + microfiber', Thickness: '6mm', Size: '183cm × 61cm', Includes: 'Carrying strap' },
  },
]

export const categories = ['All', 'Electronics', 'Accessories', 'Lifestyle']